export const splideImages = [
  // {
  //   id: 1,
  //   image: "yang_zhi_gan_lu.webp",
  //   alt: "ヨンジーガムロ",
  //   lazy: false,
  //   width: 1000,
  //   height: 1500,
  //   contain: true,
  //   fetchpriority: true,
  // },
  // {
  //   id: 2,
  //   image: "august-poster.webp",
  //   alt: "8月ポスター",
  //   lazy: true,
  //   width: 1000,
  //   height: 1500,
  //   contain: true,
  //   fetchpriority: false,
  // },
  // {
  //   id: 3,
  //   image: "mango-stamps.webp",
  //   alt: "マンゴー切手多",
  //   lazy: true,
  //   width: 1000,
  //   height: 1500,
  //   contain: false,
  //   fetchpriority: false,
  // },

  {
    id: 8,
    image: "0425_012.webp",
    alt: "ホーローバン",
    lazy: false,
    width: 1500,
    height: 1000,
    contain: false,
    fetchpriority: true,
  },
  {
    id: 9,
    image: "0425_009.webp",
    alt: "エッグタルト",
    lazy: true,
    width: 1500,
    height: 1000,
    contain: false,
    fetchpriority: false,
  },
  {
    id: 10,
    image: "0425_011.webp",
    alt: "マーラーガオ",
    lazy: true,
    width: 1500,
    height: 1000,
    contain: false,
    fetchpriority: false,
  },
];
